services:
  postgres:
    image: postgres:16
    container_name: order-management-postgres
    environment:
      POSTGRES_DB: order_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - order_management_data:/var/lib/postgresql/data

volumes:
  order_management_data: