spring.application.name=order-management

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/order_management}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

server.port=8081

jwt.secret=${JWT_SECRET:my-super-secret-key-for-order-management-app-2026}
jwt.expiration=86400000